import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
data=pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\datascience.csv\adult.csv",encoding='utf-8',encoding_errors='ignore')
print(data)
print("display top 10 first rows of dataset \n \n \n")
print(data.head(10))
print("display top 10 last rows of the dataset \n \n \n")
print(data.tail(10))
print("shape of the dataset \n ")
print(data.shape)
print("rows of the dataset: \n",data.shape[0])
print("columns of the dataset: \n " , data.shape[1])
print("info:")
print(data.info(),"\n")
print("50% data sample \n \n",data.sample(frac=0.50))
print("50% data sample with a specified number \n \n",data.sample(frac=0.50,random_state=100))
print("check to find out null data \n \n", data.isnull())
print("check to find out null data \n \n", data.isnull().sum())
print(sns.heatmap(data.isnull()))
#plt.show()
print("null-values\n",data.isin(['?']).sum())
print(data.columns)
data['workclass']=data['workclass'].replace('?',np.nan)
data['occupation']=data['occupation'].replace('?',np.nan)
data['native-country']=data['native-country'].replace('?',np.nan)
print(sns.heatmap(data.isnull()))
plt.show()
print(data.isnull().sum()*100/len(data))
print(data.dropna(how='any',inplace=True))
print(data.shape)
dup=data.duplicated().any()
print("is it true data has been duplicated",dup)
data=data.drop_duplicates()
print("shape after duplication:",data.shape)
print("statistics",data.describe())
